### ISSUE TITLE
STORY: Organize the static files in the ‘static’ directory and remove the unnecessary files.

### ISSUE THREAD

**Issue by MaorW** [Code-Collaborate-Community/tiger#129]
As an admin, I want to organize the static files, such as pictures or CSS files to subfolders in the ‘static’ directory. In addition, there are files that are not needed. I want to remove them.

**Comment by MaorW** [comment]
I'm on it

**Comment by lmilbaum** [comment]
Is that issue related to one of the stories or is it a refactoring story?

**Comment by MaorW** [comment]
It is a refactoring story. I made this issue because there are files that are not needed and I want to organize the static files. Such as logo files or css files.

**Comment by lmilbaum** [comment]
Perfect. File a refactoring story like all other stories.

**Comment by lmilbaum** [comment]
The subject is too long. Make it shorter and place the detailed description in the first comment.

**Comment by MaorW** [comment]
We decided that Saar will reorganize the static files.
