### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by lmilbaum** [Code-Collaborate-Community/tiger#13]
Implemented a basic home page (html)

**Comment by SaarCohen93** [comment]
Im on it

**Comment by SaarCohen93** [comment]
Hey Liora,
I have installed apache2 service in my VM using these commands:
```
sudo yum update
sudo yum install apache2
```
(btw using Ubuntu distro yum=apt-get)

**Comment by lmilbaum** [comment]
You can use apache for testing the home page you are preparing. But, it won't be needed as we are going to use python Flask as our web application server.

**Comment by SaarCohen93** [comment]
```
from flask import Flask
app = Flask(__name__)
@app.route("/")
def home():
    return "Hello Welcome to the Tiger Project RAWR!!"
```

**Comment by SaarCohen93** [comment]
With a little bit help from google,
how is that? :)

**Comment by lmilbaum** [comment]
I would prefer return html file instead of a string

**Comment by lmilbaum** [comment]
@SaarCohen93 Have a look at what we have today in the home page. Do you want to add something to it?

**Comment by SaarCohen93** [comment]
@lioramilbaum 
actually im stuck when trying to link flask to HTML file
my py code: 
`from flask import Flask, render_template
app = Flask(__name__)
@app.route('/')
def home():
    return render_template('home.html')
if __name__ == '__main__':
    app.run(debug=True`
![image](https://user-images.githubusercontent.com/57069701/69994676-09dc6c00-1557-11ea-8428-d8a3c4767371.png)
any ideas?

**Comment by SaarCohen93** [comment]
NVM I found the problem, just needed to put the HTML file in the templates sub directory.

**Comment by SaarCohen93** [comment]
Opened new PR for review

**Comment by SaarCohen93** [comment]
@lioramilbaum
