### ISSUE TITLE
[SendMessage] Remove send new message form from home

### ISSUE THREAD

**Issue by Nomasson** [Code-Collaborate-Community/tiger#155]
Remove the form from the home page and create new separate method for it.

**Comment by nuIISaftey** [comment]
do you have a specific vision for it or would you just like me to just create a template of html5 elements (i.e <article>, <aside>,<footer>,<header>, <main> etc ...) with some content in them.

**Comment by nuIISaftey** [comment]
the elements were retracted for some reason..  just to clarify i was referring to elements such as:
article, aside, footer, header, main etc..

**Comment by Nomasson** [comment]
@octopusShiva this has been resolved already, and continued by @BarakMerdler
