### ISSUE TITLE
Spin a VM in AWS using the same Vagrantfile

### ISSUE THREAD

**Issue by lmilbaum** [Code-Collaborate-Community/tiger#19]

**Comment by danielyakovich** [comment]
@lioramilbaum 
I'm on it.

**Comment by lmilbaum** [comment]
One of the challenging tasks....

**Comment by danielyakovich** [comment]
@lioramilbaum yeah... done everything according to https://github.com/mitchellh/vagrant-aws#usage, and still having issues loading the instance...

**Comment by lmilbaum** [comment]
@danielyakovich ping me today (if you are available)
