### ISSUE TITLE
Navigation Bar (navbar)

### ISSUE THREAD

**Issue by lmilbaum** [Code-Collaborate-Community/tiger#27]
With the following tabs:
Home
Subscribe

**Comment by Yarinh55** [comment]
On it

**Comment by Yarinh55** [comment]
Hi @lioramilbaum 
do you mean to create a template file with navbar which will be embedded in the app pages?

**Comment by Yarinh55** [comment]
Hi @lioramilbaum 
I created navbar template.
I need to render it in app.py and to link it with Home and  Subscribe pages (that not implemented yet). 
You can see my changes here: https://github.com/Yarinh55/tiger

What shoud I do to complete this issue?

**Comment by lmilbaum** [comment]
@Yarinh55 Update app.py such that it handles the subscribe route.

**Comment by lmilbaum** [comment]
@Yarinh55 Please sync/rebase your local repo with upstream latest changes.
You can find in the app.py a routing function for ('/'). Add another routing function for ('/subscribe')

**Comment by lmilbaum** [comment]
Sorry. I provided you the wrong info. Have a look at another side project, I am involved with
https://github.com/devopsloft/devopsloft/tree/master/app_s2i

**Comment by Yarinh55** [comment]
@lioramilbaum 
for start I made temporary home page to see the navbar.
updated app.py with the changes. 
There is no real route for Subscribe.
can you please take a look in my fork?
