### ISSUE TITLE
Add a Subscribe page

### ISSUE THREAD

**Issue by lmilbaum** [Code-Collaborate-Community/tiger#37]
Frontend task - Add the ability to add my email in a dedicated input box

**Comment by shirmenzely** [comment]
I will do it

**Comment by shirmenzely** [comment]
hi,  In which programming language should the code be written?
PHP it's ok?

**Comment by lmilbaum** [comment]
Our application is implemented with python Flask.  You should take it into consideration when choosing the frontend technology.

**Comment by lmilbaum** [comment]
@Omeramsc Isn't it a duplicated of your issue #51? Can you please align the effort and close the duplicated issue.

**Comment by Omeramsc** [comment]
> @Omeramsc Isn't it a duplicated of your issue #51? Can you please align the effort and close the duplicated issue.

@lioramilbaum Isn't there is a difference between subscribing for updates and contacting in order to send a private mesaage to the admins?
