### ISSUE TITLE
Add about page

### ISSUE THREAD

**Issue by bregman-arie** [Code-Collaborate-Community/tiger#43]
The page will describe what is the tiger project and what the application is all about

**Comment by VictoriaShumeruk** [comment]
I will take care of that issue.

**Comment by lmilbaum** [comment]
@VictoriaShumeruk How are you doing on this issue?

**Comment by VictoriaShumeruk** [comment]
Hi,
I wanted to do that in pair with Or. I haven't started it yet because I am not sure how to do it correct.
Am I just creating a new file and editing the script with vi function and inserting the information about the project?

**Comment by VictoriaShumeruk** [comment]
@lioramilbaum
