### ISSUE TITLE
Verify python3 is installed in the guest VM

### ISSUE THREAD

**Issue by lmilbaum** [Code-Collaborate-Community/tiger#5]
Spin the VM with vagrant and check that you have python3 installed.

**Comment by Omeramsc** [comment]
@lioramilbaum I'll take over this issue.

**Comment by Omeramsc** [comment]
> Spin the VM with vagrant and check that you have python3 installed.

@lioramilbaum I'll take over this issue.

**Comment by Omeramsc** [comment]
@lioramilbaum python 3.7.3 is indeed installed on the VM.

**Comment by lmilbaum** [comment]
perfect. we can close this issue.
