### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by lmilbaum** [Code-Collaborate-Community/tiger#6]
With instructions on how to spin the VM and destroy it.

**Comment by Yarinh55** [comment]
I'm on it.

**Comment by morbitton** [comment]
I'll be trying to do it as well

**Comment by lmilbaum** [comment]
@morbitton I have reviewed your PR and left you a review.  I have merged @Yarinh55's PR.  Will close this issue as done. You can close your PR and pull the changes.
