### ISSUE TITLE
[view messages] Create CSS for view-messages

### ISSUE THREAD

**Issue by Yarinh55** [Code-Collaborate-Community/tiger#88]

**Comment by Orcohen109** [comment]
I'll take this one
any specifics requests to the Design??

**Comment by Orcohen109** [comment]
I'm doing it with sapir hen

**Comment by Yarinh55** [comment]
collaborate with #87 
plan the look and feel and the structure of the page to support its goal of displaying messages.
You can make a sketch before develop, it can help you.

**Comment by lmilbaum** [comment]
Sapir, please add a comment

**Comment by lmilbaum** [comment]
As long as sapir is not assigned to the issue nor to the PR, she will not get credit for her efforts. FYI.

**Comment by sapirhe** [comment]
We did the issue together, me, Or and Tomer
