### ISSUE TITLE
Provision to VM to run a 'hello world' flask app

### ISSUE THREAD

**Issue by lmilbaum** [Code-Collaborate-Community/tiger#9]
When we spin the environment, we want it to execute a flask app which prints hello world.

**Comment by Omeramsc** [comment]
@lioramilbaum  I'm on it.

**Comment by Omeramsc** [comment]
@lioramilbaum Almost finished. the only problem is that the VM is missing the dependencies needed (flask). is there a way to permanently install it (other than adding a provision to run 'yum update' and 'pip flask' script on every startup)?
